version: "3"
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "${PORTAINER_HOST_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_DIR}:/data
    environment:
      TZ: "$TZ"
    restart: always  

volumes:
  portainer_data:

networks:
  default:


